# gradle/libs.versions.toml
[versions]
kotlin = "2.2.21"
clikt = "5.0.3"
okio = "3.9.1"

[libraries]
# Format: alias = { module = "group:artifact", version.ref = "version_name" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
